config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users do
    member do
      get :favorite
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts do
    collection do
      post :confirm
    end
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes , ->{ order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  has_secure_password
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments
  mount_uploader :profile_photo, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :current_user

  private
  def authenticate_user
    if current_user == nil
      flash[:notice] = "ログインが必要です！"
      redirect_to new_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user

 def create
   @comment = Comment.new(comment_params)
   @post = @comment.post
   if @comment.save
    respond_to :js
   else
     flash[:danger] = "コメントに失敗しました"
   end
 end

 def destroy
   @comment = Comment.find(params[:id])
   @post = @comment.post
   if @comment.destroy
     respond_to :js
   else
     falsh[:danger] = "コメントの削除に失敗しました"
   end
 end

 private
 def comment_params
   params.require(:comment).permit(:user_id, :post_id, :comment)
 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
  def like_params
    params.permit(:post_id)
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.includes(:photos, :user).order(created_at: :desc)
  end

  def new
     @post = Post.new
     @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.photos.present?
        @post.save
        ContactMailer.contact_mail(@post).deliver
        redirect_to posts_path
        flash[:success] = '投稿が保存されました'
      else
        redirect_to new_post_path
        flash[:danger] = '投稿に失敗しました'
      end
    end
  end

  def confirm
    @post = current_user.posts.new(post_params)
    render :new unless @post.valid?
  end


  def show
  end

  def edit
  end

  def update
   if params[:back]
     redirect_to post_path(@post)
   else
     if @post.update(post_params)
        flash[:notice] = "コメントを変更しました"
     else
        render :edit
        flash[:danger] = "コメントを変更できませんでした"
      end
        redirect_to post_path(@post)
     end
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:success] = '投稿が削除されました'
      end
    else
      flash[:danger] = '投稿の削除に失敗しました'
    end
    redirect_to posts_path(@post.user.id)
  end

  private
  def post_params
    params.require(:post).permit(:caption, photos_attributes:[:image, :image_cache]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :favorite]
  before_action :current_user?, only: [:edit]

  def index
   @users = User.all.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
     render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:success] = "ユーザー「#{@user.name}」を更新しました"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def destroy
    if @user.destroy
    redirect_to new_session_path
    flash[:danger] = "ユーザー「#{@user.name}」を削除しました"
    end
  end

  def favorite
    @likes = @user.like_posts
  end

  private
  def set_user
   @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :profile_photo, :profile_photo_cache)
  end

  def current_user?
    @user = User.find(params[:id])
    if @user != current_user
    flash[:danger] = "閲覧権限がありません"
    redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new'|| action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<a class="navbar-brand" href="#">Insta</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">

    <li class="nav-item dropdown">
    <% if logged_in? %>
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.name %>さん</a>
    <% else %>
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    こんにちは、ログイン</a>
    <% end %>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% if logged_in? %>
        <%= link_to 'マイページ', user_path(current_user.id), class: 'dropdown-item' %>
        <%= link_to "お気に入り", favorite_user_path(current_user.id), class: 'dropdown-item' %>
        <%= link_to 'ログアウト', session_path(current_user.id), method: :delete, class: 'dropdown-item', id:'header_nav_submit' %>
      <% else %>
        <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
        <%= link_to 'ログイン', new_session_path, class: 'dropdown-item' %>
      <% end %>
    </div>
  </li>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto align-items-center">
      <li>
        <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
      </li>
      <li>
        <%= link_to "投稿一覧", posts_path, class: "btn btn-primary" %>
      <li>
        <%= link_to "ユーザー一覧", users_path, class: "btn btn-primary" %>
      </li>
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
 html('<%= j render "posts/comment_list", { post: @post } %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_comment').val("");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
 html('<%= j render "posts/comment_list", { post: @post } %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
   <div class="container col-md-10">
     <div class="col-md-4">
     <% if flash[:notice] %>
       <p class="alert alert-primary"><%= flash[:notice] %></p>
     <% end %>
     <% if flash[:success] %>
       <p class="alert alert-success"><%= flash[:success] %></p>
     <% end %>
     <% if flash[:danger] %>
       <p class="alert alert-danger"><%= flash[:danger] %></p>
     <% end %>
     </div>
    </div>
     <div class="container">
       <%= yield %>
     </div>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
 <div class ="mb-2">
   <% if comment.user == current_user %>
    <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
     <strong>
       <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
     </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/confirm.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿内容の確認
      </div>
      <div class="card-body">
        <%= form_with model: @post, local: true, url: choose_new_or_edit, class: "upload-images p-0 border-0" do |f| %>
         <div class ="form-group row mt-2">
            <div class ="col-auto pr-0">
              <%= image_tag current_user.profile_photo_url, class: "post-profile-icon" %>
             </div>
             <div class ="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
             </div>
         </div>
         <div class="card-left">
           <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
         </div>
         <%= f.fields_for :photos do |i| %>
         <%= i.hidden_field :image_cache %>
          <% end %>
           <hr>
          <%= f.submit "戻る", name: "back", class:"btn btn-primary" %>
          <%= f.submit "投稿", class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        編集画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, local: true, class: "upload-images p-0 border-0" do |f| %>
         <div class ="form-group row mt-2">
            <div class ="col-auto pr-0">
              <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag @post.user.profile_photo.url, class: "post-profile-icon" %>
              <% end %>
             </div>
             <div class ="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
             </div>
         </div>
         <div class="card-left">
           <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
         </div>
          <hr>
         <%= f.submit "戻る", name: "back", class:"btn btn-primary" %>
         <%= f.submit "変更", class:"btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
            <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag post.user.profile_photo.url, class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(post.user), class: "black-color no-text-decoration",
              title: post.user.name do %>
              <strong><%= post.user.name %></strong>
            <% end %>
            <div class="index_row_icon">
              <% if post.user_id == current_user.id %>
              <%= link_to posts_path, class: "ml-auto mx-0 my-auto" do %>
                <div class="index-post-icon">
                </div>
                <% end %>
              <%= link_to edit_post_path(post), class: "ml-auto mx-0 my-auto" do %>
                <div class="edit-post-icon">
                </div>
                <% end %>
              <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
              <% end %>
            </div>

          <!-- <div class="clear"></div> -->
        </div>
        <%= link_to post_path(post) do %>
        <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <div class="row parts">
            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
            <%= link_to "", post_path(post), class:"comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前",
            post_path(post), class: "post-time no-text-decoration" %>
          <div id ="comment-post-<%= post.id.to_s %>">
             <%= render 'comment_list', { post: post } %>
          </div>
          <%= link_to time_ago_in_words(post.created_at).upcase + "前",
           post_path(post), class: "light-color post-time no-text-decoration" %>
          <hr>
          <div class ="row actions" id ="comment-form-post-<%= post.id.to_s %>">
             <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
               <%= f.hidden_field :user_id, value: current_user.id %>
               <%= f.hidden_field :post_id, value: post.id %>
               <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
             <% end %>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
  <% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, local: true, url: confirm_posts_path, class: "upload-images p-0 border-0" do |f| %>
         <div class ="form-group row mt-2">
            <div class ="col-auto pr-0">
              <%= image_tag current_user.profile_photo_url, class: "post-profile-icon" %>
             </div>
             <div class ="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
             </div>
         </div>
         <div class ="mb-3">
            <%= f.fields_for :photos do |i| %>
            <%= i.file_field :image %>
            <%= i.hidden_field :image_cache %>
            <% end %>
          </div>
           <%= f.submit "確認", class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name d-flex">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag @post.user.profile_photo.url, class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
              <div class="show_row_icon">
                <% if @post.user_id == current_user.id %>
                <%= link_to posts_path, class: "ml-auto mx-0 my-auto" do %>
                  <div class="index-post-icon">
                  </div>
                  <% end %>
                <%= link_to edit_post_path(@post), class: "ml-auto mx-0 my-auto" do %>
                  <div class="edit-post-icon">
                  </div>
                <% end %>
                <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                  <div class="delete-post-icon">
                  </div>
                <% end %>
                <% end %>
              </div>
            </div>
            <div class="m-2">
              <strong><%= @post.caption %></strong>
            </div>
            <div class =" comment-post-id">
              <div class =" m-2">
              </div>
            </div>
          </div>
          <div class =" row parts">
            <div id ="like-icon-post-<%= @post.id.to_s %>">
              <% if @post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                <% else %>
                <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
                <% end %>
              </div>
          </div>
          <div id ="like-text-post-<%= @post.id.to_s %>">
             <%= render "like_text", { likes: @post.likes } %>
           </div>
          <div class =" post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
          <hr>
        </div>
      </div>
    </div>
  </div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert-danger">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-4">
<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder:"名前", class: 'form-control' %><br>
    <%= f.email_field :email, placeholder:"メールアドレス", class: 'form-control' %><br>
    <%= f.password_field :password, placeholder:"パスワード", class: 'form-control' %><br>
    <%= f.password_field :password_confirmation, placeholder:"パスワード確認", class: 'form-control' %><br>
    <div class="field">
    <%= f.file_field :profile_photo %>
    <%= f.hidden_field :profile_photo_cache %>
   </div>
  </div>
  <%= f.submit '登録', value:'登録', class: 'btn btn-primary', id: 'user_form_submit' %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集画面</h1>
</div>

<%= render partial: 'form', locals: { user: @user } %>

app/views/users/favorite.html.erb
<% @likes.each do |like| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(like.user), class: "no-text-decoration" do %>
          <%= image_tag like.user.profile_photo.url, class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(like.user), class: "black-color no-text-decoration",
            title: like.user.name do %>
            <strong><%= like.user.name %></strong>
          <% end %>
        </div>
        <%= link_to post_path(like) do %>
        <%= image_tag like.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>
      </div>
     </div>
    </div>
 <% end %>
    

app/views/users/index.html.erb
<div class="d-flex align-items-center">
  <h1>ユーザー一覧</h1>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>登録日時</th>
      <th></th>
      <th></th>
      <th></th>
   </tr>
 </thead>
 <tbody>
   <% @users.each do |user| %>
     <tr>
       <td id=<%= "user-index__user-#{user.id}-name" %> ><%= user.name %></td>
       <td id=<%= "user-index__user-#{user.id}-email" %> ><%= user.email %></td>
       <td id=<%= "user-index__user-#{user.id}-created_at" %> ><%= user.created_at.strftime("%Y年 %m月 %d日 %H:%M:%S") %></td>
       <td><%= link_to '詳細', user_path(user.id), class: 'btn btn-primary mr-3', id: "user-index_detail-#{user.id}-submit" %></td>
       <% if user.id == current_user.id %>
       <td><%= link_to '編集', edit_user_path(user.id), class: 'btn btn-success mr-3', id: "user_index_edit-#{user.id}-submit" %></td>
       <td><%= link_to '削除', user_path(user.id), method: :delete, data: { confirm: "ユーザー「#{user.name}を削除します。よろしいでしょうか？」" }, class: 'btn btn-danger mr-3', id: "user_index_delete-#{user.id}-submit" %></td>
       <% end %>
     </tr>
   <% end %>
 </tbody>
</table>

app/views/users/new.html.erb
<div class="d-flex align-items-center">
  <h1>新規登録</h1>
</div>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert-danger">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-4">
<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder:"名前", class: 'form-control' %><br>
    <%= f.email_field :email, placeholder:"メールアドレス", class: 'form-control' %><br>
    <%= f.password_field :password, placeholder:"パスワード", class: 'form-control' %><br>
    <%= f.password_field :password_confirmation, placeholder:"パスワード確認", class: 'form-control' %>
  </div>
  <%= f.submit '登録', value:'登録', class: 'btn btn-primary', id: 'user_form_submit' %>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-wrap">
    <div class="row">
    <div class="col-md-4 text-center">
    <%= image_tag @user.profile_photo.url, class: "round-img" %>
      </div>
    <div class="col-md-8">
      <div class="row">
        <h1><%= @user.name %></h1>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "ログアウト", session_path(@user.id), method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <p>
          <%= @user.email %>
        </p>
      </div>
    </div>
  </div>
</div>